version: '3.4'

services:      
  api:
    image: api
    build:
      context: .
      dockerfile: ./Dockerfile-for-API
    ports:
      - "8001:8001"
    environment:
      - FAUNA_DB_KEY
      - GITHUB_TOKEN
    volumes:
      - /home/ubuntu/api:/api:rw
      - /home/ubuntu/api/givemyresume.github.io:/api/givemyresume.github.io:rw

  website:
    image: website
    build:
      context: .
      dockerfile: ./Dockerfile-for-Website
    ports:
      - "8000:8000"
    environment:
      - FAUNA_DB_KEY
      - API_URL
    volumes:
      - /home/ubuntu/website:/website
    depends_on:
      - api
